version: '2.0'

services:
  run-game:
    container_name: godot-run-game
    build:
      context: .
      dockerfile: Dockerfile
      args:
        godot_version: ${DOCKER_GODOT_VERSION}
        godot_suffix: ${DOCKER_GODOT_VERSION_SUFFIX}
    image: h4de5/docker-godot-3-build-and-run:latest
    restart: unless-stopped
    ports:
      - ${GAME_PORT}:${GAME_PORT}
    command: /root/workspace/build-scripts/run-game.sh ${GAME_SERVER_SCENE}
    volumes:
      - ${PATH_GAME_SOURCE}:/root/workspace/game/
      - ${PATH_GODOT_EDITOR}:/root/workspace/editor/
      # - ${PATH_GAME_EXPORTS}:/root/workspace/exports/
      # - ${PATH_GODOT_TEMPLATES}:/root/workspace/templates/
    environment:
      - DOCKER_GODOT_VERSION
      - DOCKER_GODOT_VERSION_SUFFIX
      - GAME_PORT
      # - GAME_NAME

  export-game:
    container_name: godot-export-game
    build:
      context: .
      dockerfile: Dockerfile
      args:
        godot_version: ${DOCKER_GODOT_VERSION}
        godot_suffix: ${DOCKER_GODOT_VERSION_SUFFIX}
    image: h4de5/docker-godot-3-build-and-run:latest
    # ports:
    #   - ${GAME_PORT}:${GAME_PORT}
    command: /root/workspace/build-scripts/export-game.sh ${GAME_NAME}
    volumes:
      - ${PATH_GAME_SOURCE}:/root/workspace/game/
      - ${PATH_GODOT_EDITOR}:/root/workspace/editor/
      - ${PATH_GAME_EXPORTS}:/root/workspace/exports/
      - ${PATH_GODOT_TEMPLATES}:/root/workspace/templates/
    environment:
      - DOCKER_GODOT_VERSION
      - DOCKER_GODOT_VERSION_SUFFIX
      - GAME_NAME
      # - GAME_PORT

  build-templates:
    container_name: godot-build-templates
    build:
      context: .
      dockerfile: Dockerfile
      args:
        godot_version: ${DOCKER_GODOT_VERSION}
        godot_suffix: ${DOCKER_GODOT_VERSION_SUFFIX}
    image: h4de5/docker-godot-3-build-and-run:latest
    # ports:
    #   - ${GAME_PORT}:${GAME_PORT}
    command: /root/workspace/build-scripts/build-godot.sh templates all
    volumes:
      # - ${PATH_GAME_SOURCE}:/root/workspace/game/
      # - ${PATH_GODOT_EDITOR}:/root/workspace/editor/
      # - ${PATH_GAME_EXPORTS}:/root/workspace/exports/
      - ${PATH_GODOT_TEMPLATES}:/root/workspace/templates/
    environment:
      - DOCKER_GODOT_VERSION
      - DOCKER_GODOT_VERSION_SUFFIX
      # - GAME_NAME
      # - GAME_PORT

  build-server:
    container_name: godot-build-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        godot_version: ${DOCKER_GODOT_VERSION}
        godot_suffix: ${DOCKER_GODOT_VERSION_SUFFIX}
    image: h4de5/docker-godot-3-build-and-run:latest
    # ports:
    #   - ${GAME_PORT}:${GAME_PORT}
    command: /root/workspace/build-scripts/build-godot.sh editor server
    volumes:
      # - ${PATH_GAME_SOURCE}:/root/workspace/game/
      - ${PATH_GODOT_EDITOR}:/root/workspace/editor/
      # - ${PATH_GAME_EXPORTS}:/root/workspace/exports/
      # - ${PATH_GODOT_TEMPLATES}:/root/workspace/templates/
    environment:
      - DOCKER_GODOT_VERSION
      - DOCKER_GODOT_VERSION_SUFFIX
      # - GAME_NAME
      # - GAME_PORT

  build-editor:
    container_name: godot-build-editor
    build:
      context: .
      dockerfile: Dockerfile
      args:
        godot_version: ${DOCKER_GODOT_VERSION}
        godot_suffix: ${DOCKER_GODOT_VERSION_SUFFIX}
    image: h4de5/docker-godot-3-build-and-run:latest
    # ports:
    #   - ${GAME_PORT}:${GAME_PORT}
    command: /root/workspace/build-scripts/build-godot.sh editor ${GODOT_EDITOR_OS}
    volumes:
      # - ${PATH_GAME_SOURCE}:/root/workspace/game/
      - ${PATH_GODOT_EDITOR}:/root/workspace/editor/
      # - ${PATH_GAME_EXPORTS}:/root/workspace/exports/
      # - ${PATH_GODOT_TEMPLATES}:/root/workspace/templates/
    environment:
      - DOCKER_GODOT_VERSION
      - DOCKER_GODOT_VERSION_SUFFIX
      # - GAME_NAME
      # - GAME_PORT
